---
abstract: 'POE-enabled ZeroMQ components'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0
  Test::TCP: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-ZMQ3
provides:
  POEx::ZMQ3:
    file: lib/POEx/ZMQ3.pm
    version: 0.04
  POEx::ZMQ3::Context:
    file: lib/POEx/ZMQ3/Context.pm
    version: 0
  POEx::ZMQ3::Publisher:
    file: lib/POEx/ZMQ3/Publisher.pm
    version: 0
  POEx::ZMQ3::Replier:
    file: lib/POEx/ZMQ3/Replier.pm
    version: 0
  POEx::ZMQ3::Requestor:
    file: lib/POEx/ZMQ3/Requestor.pm
    version: 0
  POEx::ZMQ3::Role::Emitter:
    file: lib/POEx/ZMQ3/Role/Emitter.pm
    version: 0
  POEx::ZMQ3::Sockets:
    file: lib/POEx/ZMQ3/Sockets.pm
    version: 0
  POEx::ZMQ3::Sockets::ZMQSocket:
    file: lib/POEx/ZMQ3/Sockets/ZMQSocket.pm
    version: 0
  POEx::ZMQ3::Subscriber:
    file: lib/POEx/ZMQ3/Subscriber.pm
    version: 0
recommends:
  Class::XSAccessor: 0
requires:
  Carp: 0
  Moo: 1.000007
  MooX::Role::POE::Emitter: 0.11
  POE: 1.3
  Storable: 0
  ZMQ::Constants: 1.02
  ZMQ::LibZMQ3: 1.06
  namespace::clean: 0.23
  perl: v5.10.1
  strictures: 1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avenj/poex-zmq3.git
version: 0.04
