---
abstract: 'POE-enabled asynchronous ZeroMQ components'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-ZMQ3
requires:
  Carp: 0
  Moo: 1.000007
  MooX::Role::POE::Emitter: 0.11
  MooX::Role::Pluggable::Constants: 0
  POE: 1.3
  POSIX: 0
  Storable: 0
  ZMQ::Constants: 1.02
  ZMQ::LibZMQ3: 1.08
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/poex-zmq3.git
version: 0.060004
